name: Production Deployment

on:
  push:
    branches:
      - 'main'

jobs:
  deploy-production:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - run: pnpm install
      - run: pnpm run db:migrate
        env: # production database URL from secrets
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
